name: mdbook-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  wait-for-build:
    name: Wait for other checks
    runs-on: ubuntu-latest
    steps:
      - name: Wait for docker build
        # Build only in template repo
        if: ${{ ${{ github.server_url }}/${{ github.repository }} == 'https://github.com/chr1st1ank/arcbook' }}
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: master
          running-workflow-name: 'Publish the package'
          check-name: "Wait for other checks"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
  publish:
    runs-on: ubuntu-latest
    needs: wait-for-build
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: ghcr.io/chr1st1ank/arcbook/mdbook-builder:latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
