name: mdbook-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  mdbook-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chr1st1ank/arcbook/mdbook-builder:latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - run: mdbook build

      - uses: actions/upload-artifact@v3
        with:
          name: 'mdbook'
          path: html

  mdbook-publish:
    runs-on: ubuntu-latest
    needs: mdbook-build
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - name: 'Download docs'
        uses: actions/download-artifact@v1
        with:
          name: 'mdbook'
          path: html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
