name: github pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: sudo apt-get install -y plantuml 

      - name: Install mdbook-mermaid
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-mermaid

      - name: Install mdbook-mermaid
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-plantuml

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
