name: mdbook-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: ghcr.io/chr1st1ank/arcbook/mdbook-builder:latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
